#!/usr/bin/env nextflow

nextflow.enable.dsl = 2


process download_bcl_from_s3 {
	//download and unzip bcl related files for testing purposes

	input:
	val(bcl_id)

	output:
	path("${bcl_id}")

	script:
	"""
	s3cmd get s3://amplicon-test-data/${bcl_id}.tar.gz
	tar -xvzf ${bcl_id}.tar.gz
	"""
}


process download_i2b_output_from_s3 {

	//download reference .bam generated by bambi i2b

	input:
	val(bcl_id)

	output:
	path("*.bam")
	
	script:
	"""
	s3cmd get s3://amplicon-test-data/${bcl_id}.test_i2b.subset.bam
	"""


}
