#!/bin/bash


Bootstrap: docker
From: ubuntu:bionic-20191029
Stage: spython-base

%post


apt-get update -y 
apt-get install -y gcc make libbz2-dev zlib1g-dev \ 
                libncurses5-dev libncursesw5-dev \
                liblzma-dev tar gzip wget xz-utils \
                pip tabix

pip install bgzip

cd /tmp

wget https://github.com/samtools/bcftools/releases/download/1.9/bcftools-1.9.tar.bz2

tar -C /tmp/  -vxjf /tmp/bcftools-1.9.tar.bz2
rm bcftools-1.9.tar.bz2
cd bcftools-1.9
make

cp -r * /usr/local/bin

cp -r * /usr/local/lib

cd /

%runscript
cd /
exec /bin/bash "$@"

%startscript
cd /
exec /bin/bash "$@"

