#!/bin/bash


Bootstrap: docker
From: ubuntu:bionic-20191029
Stage: spython-base

%post


sudo apt-get update
sudo apt-get install gcc
sudo apt-get install make
sudo apt-get install libbz2-dev
sudo apt-get install zlib1g-dev
sudo apt-get install libncurses5-dev
sudo apt-get install libncursesw5-dev
sudo apt-get install liblzma-dev


cd /tmp

wget https://github.com/samtools/bcftools/releases/download/1.9/bcftools-1.9.tar.bz2

tar -C /tmp/  -vxjf /tmp/bcftools-1.9.tar.bz2
rm bcftools-1.9.tar.bz2
cd bcftools-1.9
make

cp -r bin/* /usr/local/bin

cp -r lib/* /usr/local/lib

cd /

%runscript
cd /
exec /bin/bash "$@"

%startscript
cd /
exec /bin/bash "$@"

