#!/usr/bin/env python3

import argparse
import json
from glob import glob
from tqdm import tqdm
from pathlib import Path
import os
from multiprocessing import Pool
import csv
from collections import defaultdict

class NoConfigError(Exception):
    def __init__(self, message="""
        You must specify a path to a valid config file.
    """):
        self.message = message
        super().__init__(self.message)

class NoGenotypeFilesError(Exception):
    def __init__(self, message="""
        You must specify input genotype files.
    """):
        self.message = message
        super().__init__(self.message)

class NoBarcodeRefError(Exception):
    def __init__(self, message="""
        Please provide a config file containing a barcode_ref.
    """):
        self.message = message
        super().__init__(self.message)

class InvalidNCPUsRequested(Exception):
    def __init__(self, message="""
        You cannot request less than 1 CPU.
    """):
        self.message = message
        super().__init__(self.message)


class Barcode:
    def __init__(
        self,
        d_genotypes: dict,
        barcode_ref: dict
    ) -> None:
        self.barcode_ref = barcode_ref
        self.barcode_indicies = sorted(list(self.barcode_ref.keys()))
        self.d_genotypes = d_genotypes
        self.barcode = self._build_barcode()

    def _build_barcode(self) -> str:
        """
        1) iterate through sorted barcode indices
        2) at each position get barcode ref (chrom and locus)
        3) get genotype for position from genotype file
        4) Check if genotype missing or het and add to output string accordingly
        5) return barcode string
        """
        out_barcode = ""

        for index in self.barcode_indicies:
            d_barcode_pos = self.barcode_ref[index]
            gen = self.d_genotypes.get(d_barcode_pos["Chromosome"],{}).get(str(d_barcode_pos["Locus"]))
            if not gen or gen=="-":
                gen = "X"
            elif len(gen.split(","))>1:
                gen = "N"
            out_barcode+=gen
        return out_barcode

def output_df(
    records,
    outfile:str,
    sep="\t"
    ) -> None:
    """
    Write out barcodes to tsv file with a location provided by the user.
    """
    with open(outfile, "w+") as outBarcodes:
        writer = None
        for row in records:
            if not writer:
                fields = list(row.keys())
                writer = csv.DictWriter(outBarcodes, fieldnames=fields, delimiter="\t")
                writer.writeheader()
            writer.writerow(row)
        outBarcodes.close()


def read_genotype_file(
    genotype_file_path:str,
    barcode_ref: dict,
    deconstruct_barcode_ref:dict,
    sample_col: str
) -> dict:
    """
    Read in genotype file, extract records which are in the barcode ref into dictionary.

    Output dictionary structured as: {CHROM:{LOC:GEN}}
    """
    with open(genotype_file_path) as genotypefile:
        reader = csv.DictReader(genotypefile, delimiter="\t")
        
        d_out = defaultdict(lambda: defaultdict(dict))

        for row in reader:
            if row["Loc"] in deconstruct_barcode_ref and row["Chr"] in deconstruct_barcode_ref[row["Loc"]]:
                d_out[row[sample_col]][row["Chr"]][row["Loc"]] = row["Gen"]
        genotypefile.close()
        
    return dict(d_out)

def main(
    genotype_file_path:str,
    barcode_ref: dict,
    deconstruct_barcode_ref:dict,
    sample_col: str
    ) -> list:
    """
    1) Load genotype file into dictionary with read_genotype_file
    2) Create Barcode
    3) Output dictionary with sample name and barcode for each sample in genotype file dict
    """
    out_rows = []
    d_genotype_file = read_genotype_file(
        genotype_file_path,
        barcode_ref,
        deconstruct_barcode_ref,
        sample_col
    )

    for sample, d_sample_genotype in d_genotype_file.items():
        barcoding = Barcode(d_sample_genotype, barcode_ref)
        out_rows.append({"Sample":sample, "Barcode": barcoding.barcode})
    return out_rows

def map_main(args):
    """
    Return run of the main function with arguments
    (Implementation of multiprocessing starmap)
    """
    return main(*args)


if __name__=="__main__":
    #initialise argument parser
    parser = argparse.ArgumentParser(
        prog = "Amplicon Barcode Production",
        description = "A package to perform barcode production based on the production amplicon pipeline"
    )

    #create argparser arguments
    parser.add_argument("genotype_files", help="""
        Path to input genotype file(s)
    """)
    parser.add_argument("config", help="""
        Path to config json file
    """)
    parser.add_argument("--outfile", help="""
        Path to directory to output results (default: barcode_results.txt)
    """)
    parser.add_argument("--pbar", action="store_true", help="""
        Show a progress bar while running 
    """)
    parser.add_argument("--ncpus", type=int, help="""
        No. cpus to use in processing
    """)
    parser.add_argument("--sample_col", help="""
        Column to access for sample ID information in genotype file (default: SampleID)
    """)

    #get all arguments with a value and place into dictionary
    args = {k:v for k,v in vars(parser.parse_args()).items() if v}

    #read in config json file provided at command line, get speciation portion
    #if not provided throw error
    try:
        config = json.load(open(args.pop("config")))["barcoding"]
    except KeyError:
        raise NoConfigError

    #get the barcode ref from the config, if not present throw an error.
    try:
        barcode_ref = config.pop("barcode_ref")
    except:
        raise NoBarcodeRefError

    #populate deconstruct barcode for keying in read_genotype_file
    deconstruct_barcode_ref = defaultdict(list)
    for d in barcode_ref.values():
        deconstruct_barcode_ref[str(d["Locus"])].append(d["Chromosome"])
    
    #get list of genotype files from glob string, if genotype files not provided
    #throw error
    try:
        genotype_files = glob(args["genotype_files"])
    except KeyError:
        raise NoGenotypeFilesError

    #get optional arguments if provided, if not return default value
    outfile = os.path.abspath(args.get("outfile","./barcodes.txt"))
    sample_col = args.get("sample_col", "SampleID")
    ncpus = args.get("ncpus", 1)
    pbar = args.get("pbar", False)

    #check if ncpus is one, if so run in serial (bypass multiprocessing)
    if ncpus==1:
        #check if user has asked for pbar, if  so create iterator with tqdm
        #otherwise return iterator as is
        if pbar:
            iterator = tqdm(genotype_files)
        else:
            iterator = genotype_files

        #initialise all_samples list to collect data for each genotype file
        all_samples_out = []
        for genotype_file in iterator:
            #run a single genotype file through main
            out = main(genotype_file, barcode_ref, deconstruct_barcode_ref, sample_col)
            #append output to all_samples_out for output
            all_samples_out.append(out)
    elif ncpus > 1:
        #if ncpus >1 set up argument tuples per sample
        all_args = [(genotype_file, barcode_ref, deconstruct_barcode_ref, sample_col) for genotype_file in genotype_files]
        
        #if pbar requested create iterator with tqdm, otherwise don't
        with Pool(ncpus) as p:
            if pbar:
                all_samples_out = list(tqdm(p.imap(map_main, all_args), total=len(genotype_files)))
            else:
                all_samples_out = list(p.imap(map_main, all_args))
    else:
        raise InvalidNCPUsRequested
    
    #flatten nested list from output
    all_samples_out = [i for sublist in all_samples_out for i in sublist]
    #pass flattened list to output_df
    output_df(all_samples_out, outfile)

