bambi i2b --intensity-dir=$1/Data/Intensities \
 --basecalls-dir=$1/Data/Intensities/BaseCalls \
 --lane=$2 \
 --platform-unit=$3 \
 --read-group-id=$4_$2 \
 --study-name=$5 \
 --sample-alias=$6 \
 --threads=8 \
 --output-file=$7/step1-1.bam \
 --compression-level=0
